In [2]:
import pandas as pd
import json


data_list = []





file_path = 'rough.json'  


try:
    with open(file_path, "r") as file:
        json_data = json.load(file)
        
except FileNotFoundError:
    print(f"File '{file_path}' not found.")
except json.JSONDecodeError as e:
    print(f"Error decoding JSON in the file: {e}")
except Exception as e:
    print(f"An error occurred: {e}")



for data in json_data:
    train_number = data["trainNumber"]
    train_name = data["trainName"]
    distance = data["distance"]
    duration = data["duration"]

    duration_hours = duration


    hours, minutes = duration_hours.split(":")
    hours = int(hours)
    minutes = int(minutes)


    total_minutes = hours * 60 + minutes



    
    class_prices = [{"class": item["class"], "totalFare": item["totalFare"] , "basefare" : item["baseFare"] ,"reservationCharge" : item["reservationCharge"] , "superfastCharge" : item["superfastCharge"] , "dynamicFare" : item["dynamicFare"] , "cateringCharge" : item["cateringCharge"] , "fuelAmount" : item["fuelAmount"] , "totalConcession" : item["totalConcession"] , "tatkalFare" : item["tatkalFare"] , "serviceTax" : item["serviceTax"] , "otherCharge" : item["otherCharge"]} for item in data["pricesAndAvail"]]

    df = pd.DataFrame(class_prices)
    df["total_minutes"] = total_minutes
    df["distance"] = distance
    df["train number"] = train_number
    df["train name"] = train_name
    df = df[['train number', 'train name', 'class' , 'basefare' , 'reservationCharge' , 'superfastCharge' , 'dynamicFare' , 'cateringCharge' , 'fuelAmount' , 'totalConcession' , 'tatkalFare' , 'serviceTax' , 'otherCharge'  , 'distance' , 'total_minutes', 'totalFare']]

    data_list.append(df)


combined_df = pd.concat(data_list, ignore_index=True) # ignore_index=True to reset the index of the resultant DataFrame

In [3]:
combined_df

,train number,train name,class,basefare,reservationCharge,superfastCharge,dynamicFare,cateringCharge,fuelAmount,totalConcession,tatkalFare,serviceTax,otherCharge,distance,total_minutes,totalFare
0,22954,GUJARAT SF EXP,CC,215,40,45,0,0,0.0,0,0,15.0,0,100,99,315
1,22954,GUJARAT SF EXP,2S,50,15,15,0,0,0.0,0,0,0.0,0,100,99,80
2,22956,KUTCH EXPRESS,1A,1060,60,75,0,0,0.0,0,0,60.0,0,100,110,1255
3,22956,KUTCH EXPRESS,2A,629,50,45,0,0,0.0,0,0,36.0,0,100,110,760
4,22956,KUTCH EXPRESS,3A,443,40,45,0,0,0.0,0,0,27.0,0,100,110,555
5,22956,KUTCH EXPRESS,SL,125,20,30,0,0,0.0,0,0,0.0,0,100,110,175
6,22717,RJT SC SUP EXP,2A,629,50,45,0,0,0.0,0,0,36.0,0,100,98,760
7,22717,RJT SC SUP EXP,3A,443,40,45,0,0,0.0,0,0,27.0,0,100,98,555
8,22717,RJT SC SUP EXP,SL,125,20,30,0,0,0.0,0,0,0.0,0,100,98,175
9,22717,RJT SC SUP EXP,2S,50,15,15,0,0,0.0,0,0,0.0,0,100,98,80
10,12990,AII DDR EXPRESS,2A,629,50,45,0,0,0.0,0,0,36.0,0,100,130,760
11,12990,AII DDR EXPRESS,3A,443,40,45,0,0,0.0,0,0,27.0,0,100,130,555
12,12990,AII DDR EXPRESS,3E,443,40,45,0,0,0.0,0,0,27.0,0,100,130,555
13,12990,AII DDR EXPRESS,SL,125,20,30,0,0,0.0,0,0,0.0,0,100,130,175
14,22475,HSR CBE AC EXP,1A,1060,60,75,0,0,0.0,0,0,60.0,0,100,102,1255
15,22475,HSR CBE AC EXP,2A,629,50,45,0,0,0.0,0,0,36.0,0,100,102,760
16,22475,HSR CBE AC EXP,3A,443,40,45,0,0,0.0,0,0,27.0,0,100,102,555
17,09419,ADI TPJ SPECIAL,1A,1378,60,0,0,0,0.0,0,0,72.0,0,100,85,1510
18,09419,ADI TPJ SPECIAL,2A,1321,50,0,0,0,0.0,0,0,69.0,0,100,85,1440
19,09419,ADI TPJ SPECIAL,3A,960,40,0,0,0,0.0,0,0,50.0,0,100,85,1050
20,09419,ADI TPJ SPECIAL,SL,365,20,0,0,0,0.0,0,0,0.0,0,100,85,385

In [4]:
dummies = pd.get_dummies(combined_df['class'])
dummies

       1A     2A     2S     3A     3E     CC     SL
0   False  False  False  False  False   True  False
1   False  False   True  False  False  False  False
2    True  False  False  False  False  False  False
3   False   True  False  False  False  False  False
4   False  False  False   True  False  False  False
5   False  False  False  False  False  False   True
6   False   True  False  False  False  False  False
7   False  False  False   True  False  False  False
8   False  False  False  False  False  False   True
9   False  False   True  False  False  False  False
10  False   True  False  False  False  False  False
11  False  False  False   True  False  False  False
12  False  False  False  False   True  False  False
13  False  False  False  False  False  False   True
14   True  False  False  False  False  False  False
15  False   True  False  False  False  False  False
16  False  False  False   True  False  False  False
17   True  False  False  False  False  False  False
18  False   True  False  False  False  False  False
19  False  False  False   True  False  False  False
20  False  False  False  False  False  False   True

In [5]:
merged = pd.concat([combined_df, dummies], axis='columns')
merged

,train number,train name,class,basefare,reservationCharge,superfastCharge,dynamicFare,cateringCharge,fuelAmount,totalConcession,...,distance,total_minutes,totalFare,1A,2A,2S,3A,3E,CC,SL
0,22954,GUJARAT SF EXP,CC,215,40,45,0,0,0.0,0,...,100,99,315,False,False,False,False,False,True,False
1,22954,GUJARAT SF EXP,2S,50,15,15,0,0,0.0,0,...,100,99,80,False,False,True,False,False,False,False
2,22956,KUTCH EXPRESS,1A,1060,60,75,0,0,0.0,0,...,100,110,1255,True,False,False,False,False,False,False
3,22956,KUTCH EXPRESS,2A,629,50,45,0,0,0.0,0,...,100,110,760,False,True,False,False,False,False,False
4,22956,KUTCH EXPRESS,3A,443,40,45,0,0,0.0,0,...,100,110,555,False,False,False,True,False,False,False
5,22956,KUTCH EXPRESS,SL,125,20,30,0,0,0.0,0,...,100,110,175,False,False,False,False,False,False,True
6,22717,RJT SC SUP EXP,2A,629,50,45,0,0,0.0,0,...,100,98,760,False,True,False,False,False,False,False
7,22717,RJT SC SUP EXP,3A,443,40,45,0,0,0.0,0,...,100,98,555,False,False,False,True,False,False,False
8,22717,RJT SC SUP EXP,SL,125,20,30,0,0,0.0,0,...,100,98,175,False,False,False,False,False,False,True
9,22717,RJT SC SUP EXP,2S,50,15,15,0,0,0.0,0,...,100,98,80,False,False,True,False,False,False,False
10,12990,AII DDR EXPRESS,2A,629,50,45,0,0,0.0,0,...,100,130,760,False,True,False,False,False,False,False
11,12990,AII DDR EXPRESS,3A,443,40,45,0,0,0.0,0,...,100,130,555,False,False,False,True,False,False,False
12,12990,AII DDR EXPRESS,3E,443,40,45,0,0,0.0,0,...,100,130,555,False,False,False,False,True,False,False
13,12990,AII DDR EXPRESS,SL,125,20,30,0,0,0.0,0,...,100,130,175,False,False,False,False,False,False,True
14,22475,HSR CBE AC EXP,1A,1060,60,75,0,0,0.0,0,...,100,102,1255,True,False,False,False,False,False,False
15,22475,HSR CBE AC EXP,2A,629,50,45,0,0,0.0,0,...,100,102,760,False,True,False,False,False,False,False
16,22475,HSR CBE AC EXP,3A,443,40,45,0,0,0.0,0,...,100,102,555,False,False,False,True,False,False,False
17,09419,ADI TPJ SPECIAL,1A,1378,60,0,0,0,0.0,0,...,100,85,1510,True,False,False,False,False,False,False
18,09419,ADI TPJ SPECIAL,2A,1321,50,0,0,0,0.0,0,...,100,85,1440,False,True,False,False,False,False,False
19,09419,ADI TPJ SPECIAL,3A,960,40,0,0,0,0.0,0,...,100,85,1050,False,False,False,True,False,False,False
20,09419,ADI TPJ SPECIAL,SL,365,20,0,0,0,0.0,0,...,100,85,385,False,False,False,False,False,False,True

In [6]:
final = merged.drop(['class'], axis='columns')
final

,train number,train name,basefare,reservationCharge,superfastCharge,dynamicFare,cateringCharge,fuelAmount,totalConcession,tatkalFare,...,distance,total_minutes,totalFare,1A,2A,2S,3A,3E,CC,SL
0,22954,GUJARAT SF EXP,215,40,45,0,0,0.0,0,0,...,100,99,315,False,False,False,False,False,True,False
1,22954,GUJARAT SF EXP,50,15,15,0,0,0.0,0,0,...,100,99,80,False,False,True,False,False,False,False
2,22956,KUTCH EXPRESS,1060,60,75,0,0,0.0,0,0,...,100,110,1255,True,False,False,False,False,False,False
3,22956,KUTCH EXPRESS,629,50,45,0,0,0.0,0,0,...,100,110,760,False,True,False,False,False,False,False
4,22956,KUTCH EXPRESS,443,40,45,0,0,0.0,0,0,...,100,110,555,False,False,False,True,False,False,False
5,22956,KUTCH EXPRESS,125,20,30,0,0,0.0,0,0,...,100,110,175,False,False,False,False,False,False,True
6,22717,RJT SC SUP EXP,629,50,45,0,0,0.0,0,0,...,100,98,760,False,True,False,False,False,False,False
7,22717,RJT SC SUP EXP,443,40,45,0,0,0.0,0,0,...,100,98,555,False,False,False,True,False,False,False
8,22717,RJT SC SUP EXP,125,20,30,0,0,0.0,0,0,...,100,98,175,False,False,False,False,False,False,True
9,22717,RJT SC SUP EXP,50,15,15,0,0,0.0,0,0,...,100,98,80,False,False,True,False,False,False,False
10,12990,AII DDR EXPRESS,629,50,45,0,0,0.0,0,0,...,100,130,760,False,True,False,False,False,False,False
11,12990,AII DDR EXPRESS,443,40,45,0,0,0.0,0,0,...,100,130,555,False,False,False,True,False,False,False
12,12990,AII DDR EXPRESS,443,40,45,0,0,0.0,0,0,...,100,130,555,False,False,False,False,True,False,False
13,12990,AII DDR EXPRESS,125,20,30,0,0,0.0,0,0,...,100,130,175,False,False,False,False,False,False,True
14,22475,HSR CBE AC EXP,1060,60,75,0,0,0.0,0,0,...,100,102,1255,True,False,False,False,False,False,False
15,22475,HSR CBE AC EXP,629,50,45,0,0,0.0,0,0,...,100,102,760,False,True,False,False,False,False,False
16,22475,HSR CBE AC EXP,443,40,45,0,0,0.0,0,0,...,100,102,555,False,False,False,True,False,False,False
17,09419,ADI TPJ SPECIAL,1378,60,0,0,0,0.0,0,0,...,100,85,1510,True,False,False,False,False,False,False
18,09419,ADI TPJ SPECIAL,1321,50,0,0,0,0.0,0,0,...,100,85,1440,False,True,False,False,False,False,False
19,09419,ADI TPJ SPECIAL,960,40,0,0,0,0.0,0,0,...,100,85,1050,False,False,False,True,False,False,False
20,09419,ADI TPJ SPECIAL,365,20,0,0,0,0.0,0,0,...,100,85,385,False,False,False,False,False,False,True

In [7]:
final.to_csv("train_prices_combined.csv", index=False)